### ISSUE TITLE
Somehow the latest rsync package is not working

### ISSUE THREAD

**Issue by smorimoto** [jaalto/cygwin-package--rsync#1]

**Comment by smorimoto** [comment]
I don't know if this will help, but I just published it. https://github.com/smorimoto/cygwin-package-rsync-repro-1

**Comment by smorimoto** [comment]
Oh wait, there seems to be no problem with the package itself.

**Comment by jaalto** [comment]
Please confirm. The latest rsync binary from Cygwin setup.exe rsync-3.2.3+20200903+git9f9240b-2  (when installed), should work ok.

At least local test shows working binary.

Simply reply ok in another message

**Comment by jaalto** [comment]
Closed as resolved

**Comment by smorimoto** [comment]
Sorry for the late reply, it works now 🙂
